# Host to use for canonical URL generation (without trailing slash)
host: style-guide-test.herokuapp.com

# Header-related options
show_govuk_logo: true
service_name: Publishing guidance
service_link: https://www.larry-the-cat.service.gov.uk
phase: Prototype

# Links to show on right-hand-side of header
header_links:
  A to Z: /style-guide.html
  How to write: https://www.larry-the-cat.service.gov.uk/get-started
  Using the publishing apps: /
  Feedback: https://www.larry-the-cat.service.gov.uk/support

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false
